Repository fetch-rewards/swift-locking, pull requests merged in 2025-04, with the labels that each got.

#28 Add SPI badges to README
  README.md
Labels: documentation

#29 Remove author from file headers
  .swiftformat
  Sources/Synchronization/Macros/Locked/Locked.swift
  Sources/Synchronization/Models/LockType/LockType.swift
  Sources/SynchronizationClient/main.swift
  Sources/SynchronizationMacros/Macros/LockedMacro/LockedMacro+AccessorMacro.swift
  Sources/SynchronizationMacros/Macros/LockedMacro/LockedMacro+MacroArguments.swift
  Sources/SynchronizationMacros/Macros/LockedMacro/LockedMacro+MacroError.swift
  Sources/SynchronizationMacros/Macros/LockedMacro/LockedMacro+PeerMacro.swift
  Sources/SynchronizationMacros/Macros/LockedMacro/LockedMacro.swift
  Sources/SynchronizationMacros/Models/LockType/LockType+ParsingError.swift
  Sources/SynchronizationMacros/Models/LockType/LockType.swift
  Sources/SynchronizationMacros/SynchronizationPlugin.swift
  Tests/SynchronizationMacrosTests/Macros/LockedMacro/LockedMacro_MacroErrorTests.swift
  Tests/SynchronizationMacrosTests/Macros/LockedMacro/Locked_CheckedTests.swift
  Tests/SynchronizationMacrosTests/Macros/LockedMacro/Locked_UncheckedTests.swift
  Tests/SynchronizationMacrosTests/Macros/LockedMacro/TestHelpers/AssertMacroExpansion.swift
  Tests/SynchronizationMacrosTests/Macros/LockedMacro/TestHelpers/Diagnostic.swift
  Tests/SynchronizationMacrosTests/Models/LockType/LockTypeTests.swift
Labels: formatting

#30 Fix spelling mistake
  CONTRIBUTING.md
Labels: documentation

#31 Add more issue templates
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: documentation

#32 Add CODEOWNERS
  CODEOWNERS
Labels: ci/cd
